# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170502_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='/profile_image/', width_field='width_field'),
        ),
    ]
